apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
spec:
  selector:
    app: myapp            # <- selecciona pods de ambos deployments
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: NodePort          # en minikube es práctico; también podés usar LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp    
    spec:
      containers:
        - name: app-a
          image: maxirosanda/ejemplo1:1.0
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      part: b
  template:
    metadata:
      labels:
        app: myapp        # <- misma etiqueta compartida
        part: b
    spec:
      containers:
        - name: app-b
          image: maxirosanda/ejemplo1:1.0
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"

